[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
